Setting:
  ChanceName: # 成功率所显示的信息
    "10": "§c§n九死一生" # 低于等于 10 的概率
    "20": "§c§n如履薄冰" # 大于 10 低于等于 20 的概率
    "30": "§d§n铤而走险"
    "40": "§6§n铤而走险"
    "50": "§6§n喜忧参半"
    "60": "§6§n半斤八两"
    "70": "§e§n半斤八两"
    "80": "§a§n半斤八两"
    "90": "§a§n十拿九稳"
    "100": "§a§n百战百胜"
  Category: # 配方相关的配置
    武器: []
    防具: []
    杂项: []
    #示例: <- 类别的 名字/ID
    #  - "钻石剑" <- 类别包含的配方
  ForgeTitle:
    Title: "&a敲敲打打"
    SubTitle: "&e锻造中..."
    FadeIn: 10
    Time: 20
    FadeOut: 10
  Sounds:
    ClickInventory: UI_BUTTON_CLICK
    ForgeSuccess: BLOCK_ANVIL_USE
    ForgeFail: BLOCK_GLASS_BREAK
    ForgeTitle: BLOCK_ANVIL_LAND

# Offset characters' unicodes
# Never edit this unless you know what you are doing
offset-characters:
  font: customfishing:offset_chars
  '1': 
  '2': 
  '4': 
  '8': 
  '16': 
  '32': 
  '64': 
  '128': 
  '-1': 
  '-2': 
  '-4': 
  '-8': 
  '-16': 
  '-32': 
  '-64': 
  '-128': 
