name: CraftItem
version: ${version}
main: cn.jrmcdp.craftitem.CraftItem
authors: [ ZhiBuMiao, MrXiaoM ]
softdepend:
  - Vault
  - PlaceholderAPI
  - MythicLib
  - MMOItems
  - MythicMobs
  - ItemsAdder
  - LangUtils
  - CraftEngine
api-version: 1.13
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  CraftItem:
    aliases:
    - ci
    - dz
    description: Main Command

permissions:
  craftitem.time.default:
    default: true
