name: CraftItem
version: ${version}
main: cn.jrmcdp.craftitem.CraftItem
authors: [ ZhiBuMiao, MrXiaoM ]
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - MythicLib
  - MMOItems
  - LangUtils
api-version: 1.13
folia-supported: true
commands:
  CraftItem:
    aliases:
    - ci
    - dz
    description: Main Command

permissions:
  craftitem.time.default:
    default: true
