name: CraftItem
authors:
  - ZhiBuMiao
  - MrXiaoM
version: ${version}
main: cn.jrmcdp.craftitem.CraftItem
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - ProtocolLib
commands:
  CraftItem:
    aliases:
    - ci
    description: Main Command
